# Use root/example as user/password credentials
version: '3.3'
services:


  # http://localhost:8082/index.php/
  php-api:
    container_name: api
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/apache2